[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Victor Matekole", email = "github@matekole.com"},
]
dependencies = [
    "websockets>=12.0",
    "bitcoinlib>=0.6.14",
    "python-dotenv>=1.0.1",
    "btclib>=2023.7.12",
    "pysodium>=0.7.17",
    "pynostr>=0.6.2",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
dev = [
    "pytest>=8.0.2",
    "rich>=13.7.1",
]
[tool.black]
skip-string-normalization = true

[tool.pytest.ini_options]
pythonpath = [
  "./src"
]
