name: Deploy

on:
    push:
        branches:
            - main # Set a branch to deploy when pushed

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup PDM
              uses: pdm-project/setup-pdm@v4
              # You are now able to use PDM in your workflow
            - name: Install dependencies
              run: pdm install
            - name: Build coverage file
              run: |
                pytest =k '(not test_get_relays and not test_follow_up_req and not test_relay_connect and not test_event_bq_schema and not test_discover_relays)' --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt
            - name: Pytest coverage comment
              uses: MishaKav/pytest-coverage-comment@main
              with:
                pytest-coverage-path: ./pytest-coverage.txt
                junitxml-path: ./pytest.xml
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_PWD }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: vmatekole/decentral:latest
